### ISSUE TITLE
Preview callback will unregister DisplayListener

### ISSUE THREAD

**Issue by eneim** [android/camera#10]
I see that you will unregister the DisplayListener here in [this line](https://github.com/android/camera/blob/master/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/AutoFitPreviewBuilder.kt#L118). In my test, the first onUpdate call will remove the viewFinder and then add it again just like what the code does, but it will unregister the listener right away, so when I try to rotate the device it will never be called.

How this supposes to be?

P/S If I try to register the listener in "onViewAttached..." it will be fine.

**Comment by owahltinez** [comment]
The logic inside of `AutoFitPreviewBuilder` definitely needs work. I'll look into it, but I think that you are correct. Let's keep this issue open until I can spend some time to dig deeper.
