### ISSUE TITLE
DisplayListener will update ViewFinder on the change of ... other display?

### ISSUE THREAD

**Issue by eneim** [android/camera#11]
In the DisplayListener callback for onChanged(), I see that you will update the transform of TextureView if the change is for other logical display. Can I know why? I guess that if I attach my phone to an external display, and when that display is changed, my ViewFinder **on the phone** need to be adjusted as well. Is this correct?

**Comment by owahltinez** [comment]
Thanks for flagging. I'll take a second look at `AutoFitTextureView` so we can fix this as well as #10.
