### ISSUE TITLE
Is sample of CameraX vendor extention jar released?

### ISSUE THREAD

**Issue by michaelyang1024** [android/camera#13]

**Comment by owahltinez** [comment]
You can take a look at the code sample included in the documentation: https://developer.android.com/training/camerax/vendor-extensions

**Comment by HanderWei** [comment]
> You can take a look at the code sample included in the documentation: https://developer.android.com/training/camerax/vendor-extensions

I found code from googlesource.com

https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/camera/extensions/src/main/java/androidx/camera/extensions?autodive=0%2F%2F%2F

But I couldn't add `camera-extensins` dependency in build.gradle.

**Comment by owahltinez** [comment]
That's correct, the Maven repo does not yet contain artifacts for the vendor extensions. That will probably be part of a future release.
