### ISSUE TITLE
Photo look darker than normal camera

### ISSUE THREAD

**Issue by C2oWisComing** [android/camera#22]
Photo from camerax example look darker than from normal camera

Device : Samsung Galaxy Tab S2 (SM-T819Y)
OS : Android 7.0

Normal Camera Application
![64210966_308515680055889_4356966377278406656_n](https://user-images.githubusercontent.com/47094397/59156126-7bfc5880-8ac0-11e9-8c70-a6b562c8c09c.jpg)

CameraX Example Application
![62649352_361011381267966_5040892769015431168_n](https://user-images.githubusercontent.com/47094397/59156120-671fc500-8ac0-11e9-8b30-074ebd106e1f.jpg)

**Comment by owahltinez** [comment]
Thanks for the feedback. It sounds like the issue may not be with the sample itself, but potentially with the library, since the sample just uses the auto-brightness provided by CameraX. Can you please file a bug in the appropriate component of the Android Issue Tracker? It should be https://issuetracker.google.com/components/618491

**Comment by owahltinez** [comment]
Closing after 30+ days of inactivity.

**Comment by sarthakssg5** [comment]
> Thanks for the feedback. It sounds like the issue may not be with the sample itself, but potentially with the library, since the sample just uses the auto-brightness provided by CameraX. Can you please file a bug in the appropriate component of the Android Issue Tracker? It should be https://issuetracker.google.com/components/618491

I don't think so. This issue was present in the older repo as well but was closed due to the migration of the repo. 
[https://github.com/googlearchive/android-Camera2Basic/issues/53](url)

**Comment by thebino** [comment]
I observed the same behaviour on CameraX. Looks like its an library issue.
Bug report: https://issuetracker.google.com/issues/148045396
