### ISSUE TITLE
How to enable bokehImageCapture extension ?

### ISSUE THREAD

**Issue by AthiraRoslin** [android/camera#23]
In the developer site, enabling vendor extensions are elaborated. But when I try to use the same code, its not showing any extensions at all. Can anybody help on this ?

**Comment by AthiraRoslin** [comment]
This is the code I'm refering to,

import androidx.camera.extensions.BokehExtender

fun onCreate() {
    // Create a Builder same as in normal workflow.
    val builder = ImageCaptureConfig.Builder()

    // Create a Extender object which can be used to apply extension
    // configurations.
    val bokehImageCapture = BokehImageCaptureExtender.create(builder)

    // Query if extension is available (optional).
    if (bokehImageCapture.isExtensionAvailable()) {
        // Enable the extension if available.
        bokehImageCapture.enableExtension()
    }

    // Finish constructing configuration with the same flow as when not using
    // extensions.
    val config = builder.build()
    val useCase = ImageCapture(config)
    CameraX.bindToLifecycle(this as LifecycleOwner, useCase)
}

When I try the same, it is not importing the extensions.

**Comment by owahltinez** [comment]
@AthiraRoslin what device are you observing this behavior on?

**Comment by owahltinez** [comment]
Closing since extensions are not currently implemented in our sample. Feel free to open an issue in the AOSP issue tracker or continue the conversation in our [developer community forums](g.co/camerax/developers).
