### ISSUE TITLE
Provide example of how to use takePicture(OnImageCapturedListener)? use Intent(MediaStore.ACTION_IMAGE_CAPTURE) without File Uri?

### ISSUE THREAD

**Issue by chunhunghan** [android/camera#25]
Could you provide a demo about how to capture and handle in-memory buffer image?
Thanks.
In ImageCapture.Java , I found this snippet 

	// Wrap the ImageCapture.OnImageSavedListener with an OnImageCapturedListener so it can
	// be put into the capture request queue
	OnImageCapturedListener imageCaptureCallbackWrapper =
			new OnImageCapturedListener() {
				@Override
				public void onCaptureSuccess(ImageProxy image, int rotationDegrees) {
					Handler completionHandler = (mHandler != null) ? mHandler : mMainHandler;
					CameraXExecutors.ioExecutor()
							.execute(
									new ImageSaver(
											image,
											saveLocation,
											rotationDegrees,
											metadata.isReversedHorizontal,
											metadata.isReversedVertical,
											metadata.location,
											imageSavedListenerWrapper,
											completionHandler));
				}

				@Override
				public void onError(
						UseCaseError error, String message, @Nullable Throwable cause) {
					imageSavedListener.onError(error, message, cause);
				}
			};

How to achieve the following code in CameraX with in-memory buffer without use FileUri
    
        Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(image));
        startActivityForResult(takePictureIntent, REQUEST_TAKE_IMAGE);

or 

        val intent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
        if(intent.resolveActivity(packageManager) != null) {
            mCurrentPhotoPath = fileUri.toString()
            intent.putExtra(MediaStore.EXTRA_OUTPUT, fileUri)
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION
                    or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
            startActivityForResult(intent, TAKE_PHOTO_REQUEST)
        }

Thanks

**Comment by SakuyaCN** [comment]
```
val buffer = image!!.planes[0].buffer
                val bytes = ByteArray(buffer.capacity()).also {
                    buffer[it]
                }
```

**Comment by SakuyaCN** [comment]
```
val buffer = image!!.planes[0].buffer
val bytes = ByteArray(buffer.capacity()).also {
     buffer[it]
}
```

**Comment by chunhunghan** [comment]
My question is a little miss leading, I have update question to use Intent without File Uri.
Thanks

**Comment by owahltinez** [comment]
Hi @chunhunghan 

This is an issue with the sample, we should implement receiving the [MediaStore.ACTION_IMAGE_CAPTURE](https://developer.android.com/reference/android/provider/MediaStore#ACTION_IMAGE_CAPTURE) intent.

To implement the [MediaStore.ACTION_IMAGE_CAPTURE](https://developer.android.com/reference/android/provider/MediaStore#ACTION_IMAGE_CAPTURE) intent, you have to take care of two cases:
1. The caller passed an [EXTRA_OUTPUT](https://developer.android.com/reference/android/provider/MediaStore.html#EXTRA_OUTPUT) with a URI where the file must be saved.
2. The caller did not pass an [EXTRA_OUTPUT](https://developer.android.com/reference/android/provider/MediaStore.html#EXTRA_OUTPUT) so the Activity must return a Bitmap as part of the result data.

The result must be returned using the [setResult](https://developer.android.com/reference/android/app/Activity.html#setResult(int,%20android.content.Intent)) method of `MainActivity` before calling `finish()`.

Please let us know if you run into any issues. In a future update, we will implement this as part of the sample.
