### ISSUE TITLE
How to use Burst mode in camerax

### ISSUE THREAD

**Issue by SakuyaCN** [android/camera#29]
I didn't find a related method in ImageCapture

**Comment by pfk-beta** [comment]
Have the same problem? Should I stay with camera2 ?

**Comment by pfk-beta** [comment]
I have the same problem. Should I stay with good old camera2 api?

**Comment by SakuyaCN** [comment]
I sent an email to the CameraX developer, they told me

> CameraX does not plan to expose all Camera2 APIs. We would rather add high level API that supports certain useful scenarios.

**Comment by owahltinez** [comment]
Thanks for following up @SakuyaCN. This is not really an issue with the sample, so I'll close it for now.
