### ISSUE TITLE
Frontal flashlight

### ISSUE THREAD

**Issue by yura-shamruk** [android/camera#32]
Are you going to support frontal flashlight? (set screen brightness to max and back). I assume it would be really handy.

**Comment by owahltinez** [comment]
The sample app does not implement flash (yet). Can you please file a bug in the appropriate component of the Android Issue Tracker? It should be https://issuetracker.google.com/components/618491

Alternatively, feel free to ask your question at the CameraX developer community forums: [g.co/camerax/developers](g.co/camerax/developers)
