### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuurw** [android/camera#34]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by owahltinez** [comment]
Hi Zuur, thank you very much for your offer! I'm not sure which project you are referring to, but if it's CameraXBasic I think we already have a [very cool logo](https://github.com/android/camera/blob/4c6501e4f1cf8b31b45bc230420579dd30ff42c9/CameraXBasic/app/src/main/ic_launcher-web.png) that we created with the help of our in-house designers.

**Comment by zuurw** [comment]
Hi @owahltinez, I didnt see it.

Greetings
