### ISSUE TITLE
Black TextureView after navigation

### ISSUE THREAD

**Issue by develerik** [android/camera#35]
I use a `BottomNavigationView` to navigate between my camera fragment and another one.
On the start of my app the camera preview is loaded correctly.
If I navigate to my second fragment and back again, `CameraX` is successfully bound to the lifecycle, but the `TextureView` is black.

I can resolve this by adding `Thread.sleep(330)` before `CameraX.bindToLifecycle()` but this is a bad solution, because it adds some delay before showing the preview.

What can I do to solve this problem without this delay?

**Comment by owahltinez** [comment]
Can you please provide some code that lets us reproduce this issue?

**Comment by Tooto** [comment]
I think, its happen when u rebind camera to lifecycle.
I have black screen os some devices (ex. Alcatel 5059D) when trying to switch between front and back cameras. 
I have error in logcat:
` E/Camera: CameraDevice.onError(): 1 with error: ERROR_MAX_CAMERAS_IN_USE`

**Comment by owahltinez** [comment]
I think this issue should be at least partially alleviated with `alpha04`. Please reopen if it still reproduces, and provide specific device and code to reproduce this issue consistently.
