### ISSUE TITLE
how to close audio record when video recording

### ISSUE THREAD

**Issue by EdgarNg1024** [android/camera#36]
when the app want to video record, can let dev choose if use record audio pls?
I don't want record audio now, and don't want request record audio permission too.
But if I don't request record audio permission , the app will crash.

**Comment by owahltinez** [comment]
The sample app does not implement video record. Can you please file a bug in the appropriate component of the Android Issue Tracker? It should be https://issuetracker.google.com/components/618491

Alternatively, feel free to ask your question at the CameraX developer community forums: g.co/camerax/developers
