### ISSUE TITLE
How to specify video resolution for VideoCapture ?

### ISSUE THREAD

**Issue by Taharo** [android/camera#4]
I want to set video resolution width=540 and height=960, but resulted video has width=360 and height=640.
`        
val videoCaptureConfig = VideoCaptureConfig.Builder().apply {
            setLensFacing(lensFacing)
            setTargetRotation(viewFinder.display.rotation)
            setTargetResolution(Size(540, 960))
            setMaxResolution(Size(540, 960))
        }.build()
`

**Comment by josephteoh** [comment]
@Taharo, may I know how did you able to use VideoCapture to capture video? I tried but got an error "VideoCapture class have annotation RestrictTo(Scope.LIBRARY_GROUP)"...

**Comment by Taharo** [comment]
@josephteoh just add @SuppressLint("RestrictedApi") on your method.
`
@SuppressLint("RestrictedApi")
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
}
`

**Comment by josephteoh** [comment]
@Taharo thx, added it, but encountered other error with regards to AudioRecord....guess it's still buggy(in Java)...probably I should try Kotlin then. Thx again, sorry for the sidetrack and unable to test out your question.

**Comment by owahltinez** [comment]
@Taharo video recording is currently in preliminary stages and not officially supported, buggy and inconsistent behavior like you described here is expected at this stage.
