### ISSUE TITLE
CameraX - Preview is wrong sized and the quality is very bad on some devices

### ISSUE THREAD

**Issue by Wonderpol** [android/camera#53]
I use AutoFitPreviewBuilder in the same way as in sample but there is a problem on some devices e.g. on my Samsung s9 everything works fine but on my older(SM s6) this line: 
`val newViewFinderDimens = Size(right - left, bottom - top)` generate wrong values and there are ugly stripes(left and right side), the height is good. On my friend's phone it works well but there is another issue `updateTransform(viewFinder, rotation, it.textureSize, viewFinderDimens)` value `it.textureSize` is wrong. What can cose this problem if on some devices is everything all right. Could it be problem with CamerX API or the problem is on my side?

**Comment by claireliu14** [comment]
Did you solve the problem ?

**Comment by Wonderpol** [comment]
Hey, not at all. The problem disappears when app is made to full screen. As
I said not on every device there is a problem without full screen. But what
if I want to have status bar and good preview. I have already tried a lot
of things but without success. I think it can be connected with android
version because on phones e.g S9 S10+ works well but on e.g s6 not.

**Comment by claireliu14** [comment]
Thanks for your reply. I met the same problem on s8, too. But after changed CameraX API version to 1.0.0-alpha03, it works well for preview.

**Comment by Wonderpol** [comment]
Is your app full screen or not ?

**Comment by claireliu14** [comment]
No, I have navigation bar and transparent status bar.

**Comment by Wonderpol** [comment]
Ok  I'll try

**Comment by Wonderpol** [comment]
Hello, could you help me to do it without transparent statu bar?
I have no idea why it works like that.

śr., 21 sie 2019 o 09:09 Jasiek Piaskowy <piaskowyjasiek@gmail.com>
napisał(a):

> Ok  I'll try
>

**Comment by claireliu14** [comment]
@Wonderpol 
Maybe you can share your code and screenshot here.

**Comment by VuManhHung97** [comment]
I had the same problem. Have you edited it yet?

**Comment by VuManhHung97** [comment]
> No, I have navigation bar and transparent status bar.

How to make a preview not full screen?Can you share the code for me?
