### ISSUE TITLE
How to disable auto white balance or brightness in CameraX?

### ISSUE THREAD

**Issue by maxsdev** [android/camera#55]
When you change lighting of capturing subject, white balance on picture in preview changes. How to avoid this effect?

**Comment by amartinz** [comment]
You can use the `Camera2Config.Extender` for now to set `CaptureRequest.CONTROL_AWB_MODE`  to `CaptureRequest.CONTROL_AWB_MODE_OFF` and other values to match your needs.

An example how to use Camera2Config.Extender:

```
// Set up the view finder use case to display camera preview
val viewFinderConfigBuilder = PreviewConfig.Builder().apply {
    setLensFacing(lensFacing)
    // We request aspect ratio but no resolution to let CameraX optimize our use cases
    setTargetAspectRatio(screenAspectRatio)
    // Set initial target rotation, we will have to call this again if rotation changes
    // during the lifecycle of this use case
    setTargetRotation(viewFinder.display.rotation)
}

// Create the extender and pass in the config builder we want to extend
val previewExtender = Camera2Config.Extender(viewFinderConfigBuilder)
// Turn AWB off
previewExtender.setCaptureRequestOption(CaptureRequest.CONTROL_AWB_MODE,
        CaptureRequest.CONTROL_AWB_MODE_OFF)

// Build your config as usual and create your wanted UseCase with it
val viewFinderConfig = viewFinderConfigBuilder.build()

// Use the auto-fit preview builder to automatically handle size and orientation changes
preview = AutoFitPreviewBuilder.build(viewFinderConfig, viewFinder)
```

**Comment by maxsdev** [comment]
@amartinz Now I get an error

> IllegalArgumentException: Unsupported session configuration combination

**Comment by owahltinez** [comment]
> @amartinz Now I get an error
> 
> > IllegalArgumentException: Unsupported session configuration combination

Keep in mind that once you use Camera2 extensions, you are on your own as far as checking if the device supports the requested frame configuration -- you might be getting errors like the one reported here. This might change in the future, but using the Camera2 extensions is currently the only way to change this setting.

**Comment by ratnesh77** [comment]
Keep in mind that once you use Camera2 extensions, you are on your own as far as checking if the device supports the requested frame configuration -- you might be getting errors like the one reported here. This might change in the future, but using the Camera2 extensions is currently the only way to change this setting.

Getting Same Issue::
IllegalArgumentException: Unsupported session configuration combination

Hey how to check device support or not, can you provide me any references

**Comment by ratnesh77** [comment]
> > @amartinz Now I get an error
> > > IllegalArgumentException: Unsupported session configuration combination
> 
> Keep in mind that once you use Camera2 extensions, you are on your own as far as checking if the device supports the requested frame configuration -- you might be getting errors like the one reported here. This might change in the future, but using the Camera2 extensions is currently the only way to change this setting

Getting Same issue::
 IllegalArgumentException: Unsupported session configuration combination

How to check hardware support or not, can you give me any references

**Comment by Coolnesss** [comment]
Any setting of `captureRequest.CONTROL_AWB_MODE` crashes to ` IllegalArgumentException: Unsupported session configuration combination` here as well. Surely atleast the basic settings, e.g `DAYLIGHT` are supported on all phones? Is this a bug?

**Comment by IAn2018cs** [comment]
> Any setting of `captureRequest.CONTROL_AWB_MODE` crashes to ` IllegalArgumentException: Unsupported session configuration combination` here as well. Surely atleast the basic settings, e.g `DAYLIGHT` are supported on all phones? Is this a bug?

I found that the extension configuration was checked in androidx.camera.core.SessionConfig, and if the new configuration conflicts with the old configuration, it will throw Unsupported session configuration combination

**Comment by lunayo** [comment]
I have the same problem of trying disabling the AWB using the method above, but it does seem that CameraX has validation and does not allow overriding of config that is controlled by CameraX. Instead of trying to disable the AWB using `captureRequest.CONTROL_AWB_MODE`, I just lock the AWB using `captureRequest.CONTROL_AWB_LOCK` to get the images with consistent white balance.

**Comment by x64Dev** [comment]
Hi,
I'm also looking for a similar solution, in my case I want to change the brightness and contrast of the camera but unable to find a solution. Can any one please help me with this?

**Comment by lunayo** [comment]
@x64Dev If you need to change the brightness and contrast and setting that is specifically related to `CaptureRequest` it would be better to use directly camera2 api instead of CameraX. Apparently CameraX has limitation on doing request customisation and it would need you to rebind the use case, causing camera to restart again. I have switched CameraX to camera2 since then. The CameraBasic is very good example of that.

**Comment by x64Dev** [comment]
> @x64Dev If you need to change the brightness and contrast and setting that is specifically related to `CaptureRequest` it would be better to use directly camera2 api instead of CameraX. Apparently CameraX has limitation on doing request customisation and it would need you to rebind the use case, causing camera to restart again. I have switched CameraX to camera2 since then. The CameraBasic is very good example of that.

Thanks for the info. Why are they advertising using CameraX instead of previous Api if it's ain't ready/capable? Any way thanks for the suggestion. Let me check Camera2 then.

**Comment by huntc** [comment]
> Keep in mind that once you use Camera2 extensions, you are on your own as far as checking if the device supports the requested frame configuration -- you might be getting errors like the one reported here. This might change in the future, but using the Camera2 extensions is currently the only way to change this setting.

@owahltinez @amartinz  - I notice that the `PreviewConfig.Builder` no longer exists for CameraX beta3. Any update in terms of what must now be done to set the underlying Camera2 configuration?

**Comment by lunayo** [comment]
> > Keep in mind that once you use Camera2 extensions, you are on your own as far as checking if the device supports the requested frame configuration -- you might be getting errors like the one reported here. This might change in the future, but using the Camera2 extensions is currently the only way to change this setting.
> 
> @owahltinez @amartinz - I notice that the `PreviewConfig.Builder` no longer exists for CameraX beta3. Any update in terms of what must now be done to set the underlying Camera2 configuration?

You could try this
`val analysisExtend = Camera2Interop.Extender(builder)
 analysisExtend.setCaptureRequestOption(CaptureRequest.CONTROL_AWB_LOCK,
 false)`
