### ISSUE TITLE
Should TextureView be released when preview use case is no more used?

### ISSUE THREAD

**Issue by nominalista** [android/camera#6]
I found in the `Preview` class documentation:

> It is the application's responsibility to release the last SurfaceTexture returned by Preview.PreviewOutput.getSurfaceTexture() when a new SurfaceTexture is provided via an update or when the user is finished with the use case.

Does it mean that in `onDestroyView` along with `unbindAll`, the `SurfaceTexture` of `viewFinder` shouldn't be released?

**Comment by owahltinez** [comment]
@nominalista releasing the SurfaceTexture is unnecessary in `onDestroyView` because all children views should get destroyed with it.

**Comment by nominalista** [comment]
@owahltinez clear. Thanks for explanation! This issue can be closed I think.
